### ISSUE TITLE
Create an official image in docker hub

### ISSUE THREAD

**Issue by pgbezerra** [monitoringartist/zapix#2]
With the docker file created we could have an official and automated build in monitoringartist namespace.
Would be very nice. Thank you!

**Comment by jangaraj** [comment]
Actually, I prefer GitHub pages version to be used by the public. There is a minimum user cases, where Docker image will be useful. It's only JS/HTML/CSS, so even nginx is not required = users can clone the project and open index.html in the browser directly.
If you really need ready public Docker image, then Zapix is already available as integrated XXL extension in https://github.com/monitoringartist/zabbix-xxl.
