### ISSUE TITLE
cannot connect "error" message Zabbix 2.2

### ISSUE THREAD

**Issue by gabricar** [monitoringartist/zapix#5]
Hi, I deployed the docker container and I'm trying to connect but I'm not getting much luck.... message is "error" when I try to loggin on Zabbix 2.2 for Zabbix 3.0 it works fine.

docker logs shows nothing.

Any idea? I'm upgrading my environment but I'd like to use it with zabbix 2.2 until I get it upgraded.

Using url like: http://xxx.xxx.xxx.xxx/zabbix some as I have for zabbix 3.0, credentials are OK.

thx a lot.

**Comment by jangaraj** [comment]
That's a browser app, check the browser console. I guess 2.2 has different login method.
